# This is a basic workflow to help you get started with Actions

name: Kindling-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, release-*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  builddrives:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: Kindling-project/agent-libs.git
          ref: kindling-dev
          
      - name: setup-docker
        # You may pin to the exact commit or the version.
        # uses: docker-practice/actions-setup-docker@9fafeb38361d5d48e5afc207293715e023b6cfe0
        uses: docker-practice/actions-setup-docker@1.0.9
        
      - name: install kernel headers
        run: sudo apt-get -y install linux-headers-$(uname -r)
        
      - name: trigger compiling drivers
        run: docker run -v /usr:/host/usr -v /lib/modules:/host/lib/modules -v $PWD:/source kindlingproject/kernel-builder:latest
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
           pwd
           uname -r
           ls -l kindling-falcolib-probe/
           
  buildprobes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: copy drivers to probe
        run: |
          tar -cvzf kindling-falcolib-probe.tar.gz kindling-falcolib-probe/
          cp kindling-falcolib-probe.tar.gz probe/deploy/
      - name: test
        run: |
          ls -l ./
          cd probe/
          sh run_docker_bpf_daemon.sh
          sed -i ".bak"  's/tag = "latest"/tag = "testv1"/g' src/probe/BUILD.bazel
          bazel build -s --config=clang src/probe:push_image_localdriver
          ./bazel-bin/src/probe/push_image_localdriver 

